package gui;

import aplicacion.CallbackClientImpl;
import aplicacion.CallbackClientInterface;
import aplicacion.CallbackServerInterface;
import java.rmi.Naming;

public class VConexion extends javax.swing.JFrame {
    
    private FachadaGUI padre;

    /**
     * Creates new form VConexion
     * @param padre
     */
    public VConexion(FachadaGUI padre) {
        this.padre = padre;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PortField = new javax.swing.JTextField();
        HostField = new javax.swing.JTextField();
        ConButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jLabel1.setText("Puerto:");

        jLabel2.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jLabel2.setText("Host:");

        ConButton.setText("Conectarse");
        ConButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PortField)
                            .addComponent(HostField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(ConButton)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(PortField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(HostField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(ConButton)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConButtonActionPerformed
        if(PortField.getText().length() > 0 && HostField.getText().length() > 0){
            try {
                int RMIPort;         
                String hostName;
                hostName = HostField.getText();
                RMIPort = Integer.parseInt(PortField.getText()); 
                String registryURL = 
                    "rmi://localhost:" + PortField.getText() + "/callback";  
                // find the remote object and cast it to an 
                // interface object
                CallbackServerInterface h =
                  (CallbackServerInterface)Naming.lookup(registryURL);
                //System.out.println("Lookup completed " );
                //System.out.println("Server said " + h.sayHello());
                CallbackClientInterface callbackObj = 
                    new CallbackClientImpl(padre);
                // register for callback
                padre.iniciarSesion(callbackObj, h);
                
            } // end try 
            catch (Exception e) {
                System.out.println(
                    "Exception in VConexion: " + e);
            } // end catch
        }
        this.dispose();
    }//GEN-LAST:event_ConButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConButton;
    private javax.swing.JTextField HostField;
    private javax.swing.JTextField PortField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
